import type { Metadata } from 'next'
import {Familjen_Grotesk } from 'next/font/google'
import './globals.css'

const fam = Familjen_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Kerala Blasters',
  description: 'Generated by create next app',
  icons:{
    icon:"/kbfc_logo.svg"
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#0a0a0a]' >{children}</body>
      {/* <link rel="icon" href="/logo.svg" sizes="64x64" /> */}
    </html>
  )
}
