export const data =[
  {
    id:1,
    url:'https://www.indiansuperleague.com/static-assets/waf-images/05/c0/99/16-9/Xqa9UruFf0.png?v=100.24&w=1200',
    title:'HOME DISCOMFORT TO HOME DELIGHT: KERALA BLASTERS FC HAVE MADE KOCHI A FORTRESS',
    cut:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create...',
    description:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.'+'\n'+'The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create during every match has won admirers far beyond Kerala and even India. Kerala Blasters FC’s home ground produces one of the best atmospheres in the ISL and both the KBFC and opponent players have vouched for it. However, the home side haven’t always been able to profit from it. Kerala Blasters FC have traditionally struggled at the venue despite such a strong backing. The Yellow Army have won just 28 out of the 64 ISL matches at the venue which is approximately 44% of the matches.However, since the start of last season, Kerala Blasters FC have significantly turned their fortunes at Kochi around and now rely on their home games to fuel their playoffs charge. The most obvious difference between previous seasons and the two campaigns is the presence of head coach Ivan Vukomanovic in the Kerala Blasters FC dugout. The Serbian has managed to connect with the fans like no other coach in the past and that warmth has transferred to the players.',
    date:'11 November, 2023',
  },
  {
    id:2,
    url:'https://www.indiansuperleague.com/static-assets/waf-images/05/c0/99/16-9/Xqa9UruFf0.png?v=100.24&w=1200',
    title:'HOME DISCOMFORT TO HOME DELIGHT: KERALA BLASTERS FC HAVE MADE KOCHI A FORTRESS',
    cut:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create...',
    description:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.'+'\n'+'The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create during every match has won admirers far beyond Kerala and even India. Kerala Blasters FC’s home ground produces one of the best atmospheres in the ISL and both the KBFC and opponent players have vouched for it. However, the home side haven’t always been able to profit from it. Kerala Blasters FC have traditionally struggled at the venue despite such a strong backing. The Yellow Army have won just 28 out of the 64 ISL matches at the venue which is approximately 44% of the matches.However, since the start of last season, Kerala Blasters FC have significantly turned their fortunes at Kochi around and now rely on their home games to fuel their playoffs charge. The most obvious difference between previous seasons and the two campaigns is the presence of head coach Ivan Vukomanovic in the Kerala Blasters FC dugout. The Serbian has managed to connect with the fans like no other coach in the past and that warmth has transferred to the players.',
    date:'11 November, 2023',
  },
  {
    id:4,
    url:'https://www.indiansuperleague.com/static-assets/waf-images/05/c0/99/16-9/Xqa9UruFf0.png?v=100.24&w=1200',
    title:'HOME DISCOMFORT TO HOME DELIGHT: KERALA BLASTERS FC HAVE MADE KOCHI A FORTRESS',
    cut:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create...',
    description:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.'+'\n'+'The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create during every match has won admirers far beyond Kerala and even India. Kerala Blasters FC’s home ground produces one of the best atmospheres in the ISL and both the KBFC and opponent players have vouched for it. However, the home side haven’t always been able to profit from it. Kerala Blasters FC have traditionally struggled at the venue despite such a strong backing. The Yellow Army have won just 28 out of the 64 ISL matches at the venue which is approximately 44% of the matches.However, since the start of last season, Kerala Blasters FC have significantly turned their fortunes at Kochi around and now rely on their home games to fuel their playoffs charge. The most obvious difference between previous seasons and the two campaigns is the presence of head coach Ivan Vukomanovic in the Kerala Blasters FC dugout. The Serbian has managed to connect with the fans like no other coach in the past and that warmth has transferred to the players.',
    date:'11 November, 2023',
  },
  {
    id:3,
    url:'https://www.indiansuperleague.com/static-assets/waf-images/05/c0/99/16-9/Xqa9UruFf0.png?v=100.24&w=1200',
    title:'HOME DISCOMFORT TO HOME DELIGHT: KERALA BLASTERS FC HAVE MADE KOCHI A FORTRESS',
    cut:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create...',
    description:'The Blasters have lost just once in their last 11 home matches and have based their playoff bid on their home form.'+'\n'+'The Jawaharlal Nehru stadium in Kochi has been a sight to behold every time Kerala Blasters FC have set foot on it since the beginning of the Indian Super League (ISL) in 2014.The sea of yellow that the Kerala Blasters FC faithful create during every match has won admirers far beyond Kerala and even India. Kerala Blasters FC’s home ground produces one of the best atmospheres in the ISL and both the KBFC and opponent players have vouched for it. However, the home side haven’t always been able to profit from it. Kerala Blasters FC have traditionally struggled at the venue despite such a strong backing. The Yellow Army have won just 28 out of the 64 ISL matches at the venue which is approximately 44% of the matches.However, since the start of last season, Kerala Blasters FC have significantly turned their fortunes at Kochi around and now rely on their home games to fuel their playoffs charge. The most obvious difference between previous seasons and the two campaigns is the presence of head coach Ivan Vukomanovic in the Kerala Blasters FC dugout. The Serbian has managed to connect with the fans like no other coach in the past and that warmth has transferred to the players.',
    date:'11 November, 2023',
  },

]